### ISSUE TITLE
Download as csv has several issues

### ISSUE THREAD

**Issue by jadbaz** [alerta/alerta-webui#272]
**Issue Summary**
Here are a few issues with the new "Download as csv" feature (#263, #270):
- "Attributes" column shows as "[object Object]"
- Some columns are out of order
- Columns gradually shift from their headers

**Environment**
- Web UI: 7.4.2
- API: 7.4

**To Reproduce**
Go to [beta.alerta.io](https://beta.alerta.io) and download as csv

**Files and Screenshots**
- [Alerts_ALL.csv.txt](https://github.com/alerta/alerta-webui/files/4116112/Alerts_ALL.csv.txt)
- ![image](https://user-images.githubusercontent.com/11090042/73159315-ecf38d80-40ee-11ea-8e18-308bfeb89323.png)
- ![image](https://user-images.githubusercontent.com/11090042/73159346-fc72d680-40ee-11ea-92cf-6d7ae4afa0c0.png)

**Investigation**
- One of the issues is that some columns contain commas and are not quoted so they appear as multiple columns

**Comment by satterly** [comment]
CSV is notoriously difficult to implement which is why I chose to use a library instead of rolling my own. It looks like this library doesn't support arrays or strings with commas -- which is a common failing of csv exporters. I'll need to look into this in more detail.

**Comment by satterly** [comment]
Should be fixed. I needed to pre-format the alert data before calling export.

**Comment by jadbaz** [comment]
I can see things changed but I just downloaded alerts from beta.alerts.io and I can still see discrepancies

![image](https://user-images.githubusercontent.com/11090042/73243966-884d3700-41b1-11ea-832d-048e09620899.png)

**Comment by satterly** [comment]
There's a bug in the library if a column is an empty string it skips it. This seems to be the case for `rawData` and possibly others. See https://github.com/javiertelioz/angular2-csv/issues/75

**Comment by jadbaz** [comment]
This library seems to be stale and issues are piling up
Have you considered alternatives like [github.com/zemirco/json2csv](https://github.com/zemirco/json2csv)? This seems quite robust

**Comment by satterly** [comment]
I've just realised it's not the library. The library is fine. It was the rawData field was being passed to the csv exporter as a list when it should have been a string. I'm about to merge a fix.

**Comment by satterly** [comment]
The fix was a hack on the frontend when it should really be a change in the API. This fix will do for now however I'll make a note to review the data type of the `rawData` attribute.

**Comment by escoand** [comment]
I use Excel 2016 and the colums are not seperated when I open the exported file. I've had good results with adding an seperator definition line at the begining: https://stackoverflow.com/a/40720116/3775041
